MONGODB_URL = "mongodb+srv://tuanpluss02:Tuan2002@cluster0.sx8rjmt.mongodb.net/test"
MONGODB_DB_NAME = "chat_app"
MAX_CONNECTIONS_COUNT = 10
MIN_CONNECTIONS_COUNT = 1
JWT_TOKEN_PREFIX = "/api"
SECRET_KEY = ""
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7  # one week
ACCOUNT_SID = ""
API_KEY_SID = ""
API_KEY_SECRET = ""
